spring:
  application:
    name: rest-read-players
  jackson:
    time-zone: "America/Montevideo"
    serialization:
      write-dates-as-timestamps: false
server:
  port: 9774
  servlet:
    context-path: /read-auf-players/v1
